server: 
  port: 9090
#server.port=9090

#spring.datasource.driver-class-name
spring: 
  datasource: 
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: SPRING
    password: SPRING
  thymeleaf:
    enabled: true

# spring.mvc.view.prfix/suffix    
#  mvc: 
#    view:
#      suffix: .jsp
#      prefix: /WEB-INF/views/   



# mutlipartfile설정하기
  servlet:
    multipart:
      max-file-size: 10MB  
#mybatis: 
#  mapper-locations: classpath:mappers/**/*.xml
#  config-location: classpath:config/mybatis-config.xml
  
logging:
  file: 
    name: logs/springboot.log
  level:
    '[com.bs.firstboot]': debug

#사용자가 지정한 내용
linux: 
  home: /home/goodee
  url: 14.36.141.71:1234
  
#환경변수의 값을 불러와 저장
window:
  javahome: ${JAVA_HOME} 
    




           